export const ADD_COLOR_BOX_ROW = "ADD_COLOR_BOX_ROW";
export const REMOVE_COLOR_BOX_ROW = "REMOVE_COLOR_BOX_ROW";
export const GET_COLOR_BOX_ROW = "GET_COLOR_BOX_ROW";
export const ACTIVATE_COLOR_BOX = "ACTIVATE_COLOR_BOX";
export const DEACTIVATE_COLOR_BOX = "DEACTIVATE_COLOR_BOX";
export const CHANGE_COLOR_BOX = "CHANGE_COLOR_BOX";
export const CHANGE_COLOR_BOX_LCH = "CHANGE_COLOR_BOX_LCH";
export const RECALCULATE_CONTRAST = "RECALCULATE_CONTRAST";